### PR TITLE
Change outside temp from uint8 to int8 in two places to support negative outside temp

### PR DESCRIPTION
**Pull request by cheitzig**
This pull request fixes issue #15

### CODE REVIEW

**Comment by acd** [comment]
Can you run go fmt on this change to fix the formatting?  Happy to merge after.  Thx.

**Comment by cheitzig** [comment]
Hey sorry, I never saw your reply. I'll figure out what you mean about go fmt and re-upload.

**Comment by cheitzig** [comment]
Closing this pull request and creating a new pull request with properly formatted files.

**Comment by cheitzig** [comment]
I think I fixed the formatting. Please merge.

**Review by maximvoven — APPROVED** [review]
The Formatting is Correct, and pr addresses the issue described in #15.

**Comment by acd** [comment]
Merged manually

**Pull request closed without merging**
